blog/urls.py
from django.urls import path
from . import views
#from .views import AddPostView
from django.views.generic import TemplateView

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    # ALTERNATIVE path('post/new/', AddPostView.as_view(), name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('drafts/', views.post_draft_list, name='post_draft_list'),
    path('post/<pk>/publish', views.post_publish, name='post_publish'),
    path('post/<pk>/remove', views.post_remove, name='post_remove'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
    path('category/add/', views.AddCategoryView.as_view(), name='add_category'),
    path('category/<str:category>', views.category_view, name='category'),
    path('not_allowed!/', TemplateView.as_view(template_name='blog/not_allowed.html'), name='not_allowed'),
    path('post/<int:pk>/invalid_author', views.post_invalid_author, name='invalid_author')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views
from blog import views as blog_views

handler403 = blog_views.handler403

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('cv/', include('online_cv.urls')),
]

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.urls import reverse
from ckeditor.fields import RichTextField
# Create your models here.

# NOTE: My first django model! Pog!
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = RichTextField(blank=True, config_name='blog')
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    category = models.CharField(max_length=255, default='uncategorised')

    def publish(self):
        self.published_date = timezone.now()
        self.save()
        
    # Added in order to count number of approved comments in post list
    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

    def __str__(self):
        return self.title

######################
class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('post_list')

######################
class Comment(models.Model):
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Post, Comment, Category
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column

#choices = [('programming', 'Programming'), ('technology', 'Technology'), ('gaming', 'Gaming')]

class PostForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Make sure choices selection gets updated every time page is loaded
        self.fields['category'].widget.choices = Category.objects.all().values_list('name','name')
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('title', css_class='form-group col-md-8 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('category', css_class='form-group col-md-3 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('text', css_class='form-group col-md-15 mb-0'),
                css_class='form-row'
            ),
            Submit('save_as_draft', 'Save as draft', css_class="btn btn-secondary"),
            Submit('save_and_publish', 'Save and publish', css_class="btn btn-secondary")
        )

    class Meta:
        choices = Category.objects.all().values_list('name','name')
        model = Post
        fields = ('title', 'category', 'text',)
        widgets = {
             'title': forms.TextInput(attrs={'class': 'form-control'}),
             'category': forms.Select(choices=choices, attrs={'class': 'form-control'}),
         }

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text',)
        widgets = {
            'author': forms.TextInput(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'form-control'}),
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.utils import timezone
from django.views.generic import ListView, DetailView, CreateView
from .models import Post, Comment, Category
from .forms import PostForm, CommentForm
from .decorators import unauthenticated_user, allowed_users

# Create your views here.
# NOTE: My first view creation :o
def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    category_menu = Category.objects.all()
    return render(request, 'blog/post_list.html', {'posts': posts, 'category_menu': category_menu})

# Must make sure the extra arg has the EXACT same name as in urls.py. Is this django-only? Or python?
def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    category_menu = Category.objects.all()
    return render(request, 'blog/post_detail.html', {'post': post, 'category_menu': category_menu})

# New post form page
@login_required
@allowed_users(allowed_roles=['admin', 'author'])
def post_new(request):
    category_menu = Category.objects.all()
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False) # Commit false so can add author before save
            post.author = request.user
            if 'save_and_publish' in request.POST:
                post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form, 'category_menu': category_menu})

# Alternative postnew view! NOTE: NOT IN USE (also should learn about mixins)
class AddPostView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post_edit.html'
    #fields = '__all__'
    #fields = ('title', 'text')

# Edit existing post page
@login_required
@allowed_users(allowed_roles=['admin', 'author'])
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    category_menu = Category.objects.all()
    if request.user == post.author or request.user.groups.filter(name='admin').exists():
        if request.method == "POST":
            form = PostForm(request.POST, instance=post)
            if form.is_valid():
                post = form.save(commit=False)
                post.author = request.user
                if 'save_and_publish' in request.POST:
                    post.published_date = timezone.now()
                post.save()
                return redirect('post_detail', pk=post.pk)
        else:
            form = PostForm(instance=post)
        return render(request, 'blog/post_edit.html', {'form': form, 'post': post, 'category_menu': category_menu})
    else:
        return redirect('invalid_author', pk=post.pk)

# Show unpublished posts
@login_required
@allowed_users(allowed_roles=['admin', 'author'])
def post_draft_list(request):
    posts = Post.objects.filter(published_date__isnull=True).order_by('-created_date')
    return render(request, 'blog/post_draft_list.html', {'posts': posts})

# Publish draft post
@login_required
@allowed_users(allowed_roles=['admin', 'author'])
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user == post.author or request.user.groups.filter(name='admin').exists():
        post.publish()
        return redirect('post_detail', pk=pk)
    else:
        return redirect('invalid_author', pk=post.pk)

# Delete existing post
@login_required
@allowed_users(allowed_roles=['admin', 'author'])
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user == post.author or request.user.groups.filter(name='admin').exists():
        post.delete()                           # Model.delete is standard django method.
        return redirect('post_list')
    else:
        return redirect('invalid_author', pk=post.pk)

def post_invalid_author(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/invalid_author.html', {'post': post})

# Add comment to post           TODO: If user is logged in, change form such that name field not required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            if request.user.is_authenticated:
                comment.approve()
            comment.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html', {'form': form})

@login_required
@allowed_users(allowed_roles=['admin'])
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('post_detail', pk=comment.post.pk)

@login_required
@allowed_users(allowed_roles=['admin'])
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('post_detail', pk=comment.post.pk)

# Add category NOTE: TRYING OUT CLASS VIEWS
class AddCategoryView(PermissionRequiredMixin, CreateView): # We have to include mixin arg instead of equivalent decorator.
    permission_required = 'blog.add_category'
    model = Category
    template_name = 'blog/add_category.html'
    fields = '__all__'

def category_view(request, category):
    category_posts = Post.objects.filter(category__iexact=category.replace('-', ' '), published_date__lte=timezone.now()).order_by('-published_date')
    category_menu = Category.objects.all()
    return render(request, 'blog/categories.html', {'category': category.title().replace('-', ' '), 'category_posts': category_posts, 'category_menu': category_menu})

def handler403(request, exception):
    return render(request, '403.html')

blog/templates/blog/add_category.html
{% extends 'blog/base.html' %}

{% block title %}
  George's Blog - Add a new category
{% endblock %}

{% block content %}
</br>
<div class="content container">
	<div class="row">           
		<div class="col-md-8">  
			{% if perms.post.manage_posts %}
			<h2>New Category</h2>
			<div class="form-group">
				<form method="POST" class="post-form">{% csrf_token %}
					<input type="text" class="form-control" name="name" maxlength="255" required="" id="id_name" placeholder="Category Name">
				</br>
					<button id="save_post" type="submit" class="btn btn-secondary" >Add Category</button>
				</form>
			</div>
			{% else %}
			You are not allowed to do this action!
			{% endif %}
		</div>
	</div>
</div>
{% endblock %}

blog/templates/blog/add_comment_to_post.html
{% extends 'blog/base.html' %}

{% block title %}
  George's Blog - New comment
{% endblock %}

{% block content %}
</br>
<div class="content container">
  <div class="row">           
    <div class="col-md-8">  
      <h1>New comment</h1>
      <form method="POST" class="post-form">{% csrf_token %}

        <div class="form-group">
          <label for="id_author">Username:</label>
          {% if user.username %}
            <input type="text" name="author" class="form-control" value="{{ user.username }}" required="" id="id_author" readonly>
            <small id="username_tooltip" class="form-text text-muted">Change your username here.</small>
            
          {% else %}
          <input type="text" name="author" class="form-control" maxlength="200" required="" id="id_author">
          <small id="login_new_user" class="form-text text-muted">You are not currently signed in.<br>
            You can still submit a comment, but it won't be shown until it's been approved.<br>
            <a href="{% url 'login' %}"">Login</a> or <a href="{% url 'register' %}"">sign up</a> to post your comment immediately!</small>
          {% endif %}
        </div>

        <div class="form-group">
          <label for="id_text">Text:</label>
          <textarea name="text" cols="40" rows="10" class="form-control" required="" id="id_text"></textarea>
        </div>
        <button type="submit" class="btn btn-secondary" id="comment_submit">Submit</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
{% load blog_extras %}
<html>
  <head>
    <title>
      {% block title %}
        George Kirkman's Blog
      {% endblock %}
    </title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <!-- FontAwesome 5 icons-->
    <script src="https://kit.fontawesome.com/88e5663567.js" crossorigin="anonymous"></script>
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <!-- Tab icon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />
    <!-- Code Prettify for nicer code snippets -->
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js?skin=sunburst"></script>
  </head>

  
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="/">George's Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/"><i class="fas fa-home"></i> Home <span class="sr-only">(current)</span></a>
                </li>
                <!-- Settings Dropdown -->
                {% if perms.blog.manage_posts %}
                  <li>
                      <a class="nav-link" href="/admin"><i class="fas fa-cog"></i> Admin Settings</a>
                  </li>
                {% endif %}
                {% if request.user|has_group:"author" or request.user|has_group:"admin" %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'post_new' %}" id="post_new_button"><i class="fas fa-edit"></i> New Post</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'post_draft_list' %}" id="view_drafts_button"><i class="fas fa-file"></i> View Drafts</a>
                  </li>
                {% endif %}
                <!-- Categories Dropdown -->
                {% if category_menu %}
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-folder"></i> Categories
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      {% for category in category_menu %}
                        <a class="dropdown-item" href="{% url 'category' category|slugify %}">{{ category }}</a>
                      {% endfor %}
                      {% if perms.blog.add_category %}
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'add_category' %}" id="id_add_category"><i class="fas fa-folder-plus"></i> Add Category</a>
                      {% endif %}
                    </div>
                  </li>
                  {% elif perms.blog.add_category %}
                  <a class="nav-link" href="{% url 'add_category' %}" id="id_add_category"><i class="fas fa-folder-plus"></i> Add Category</a>
                {% endif %}
            </ul>
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'cv_builder' %}" id="cv_builder"><i class="fas fa-briefcase"></i> CV Builder</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item dropdown" id="id_account_dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="fas fa-user"></i> {{ user.username|title }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'logout' %}" id="id_logout"><i class="fas fa-sign-out-alt"></i> Log out</a>
                </div>
              </li>
              {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'login' %}" id="login_button"><i class="fas fa-sign-in-alt"></i> Login</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'register' %}" id="signup_button"><i class="fas fa-user-plus"></i> Register</a>
                </li>
              {% endif %}
            </ul>
        </div>
    </nav>
  
    {% block content %} <!-- this is where we can inject blocks of html code from other files!-->
    {% endblock %}      

    {% block javascript %}
    {% endblock %}
  </body>
</html>

blog/templates/blog/categories.html
{% extends 'blog/base.html' %}

{% block content %}  
</br>
<div class="content container">
  <div class="row">           
    <div class="col-md-8">  
    {% if category_posts %}
      <h1>{{ category }} Posts</h1>
      {% for post in category_posts %}
        <div class="post">
            <h2><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
            <div class="date">
              <small>published: {{ post.published_date }}</small>
          </div> 
            <p>{{ post.text|slice:":200"|safe }}...</p>
            <a href="{% url 'post_detail' pk=post.pk %}">Comments: {{ post.approved_comments.count }}</a>
            <hr>
        </div>
      {% endfor %}
    {% else %}
      <h2>Sorry, there are currently no blog posts in this category.</h2>
    {% endif %}
    </div>
  </div>
</div>
{% endblock %}

blog/templates/blog/invalid_author.html
{% extends 'blog/base.html' %}

{% block title %}
  George's Blog: Invalid Author
{% endblock %}

{% block content %}
</br>
<div class="content container">
  <div class="row">           
    <div class="col-md-8">  
      <h3>You are not the author of this post!</h3>
      <p>This post belongs to {{ post.author.first_name }} {{ post.author.last_name }} (username: {{ post.author }}).</p>
      <p>Click <a href="/">here</a> to return to the homepage, or <a href="{% url 'logout' %}">log out</a> and try again with the correct account.</p>
    </div>
  </div>
</div>
{% endblock %}

blog/templates/blog/not_allowed.html
{% extends 'blog/base.html' %}

{% block content %}
</br>
<div class="content container">
  <div class="row">           
    <div class="col-md-8">  
      <h3>You are not allowed to view this page!</h3>
      <p>How'd you sneak in here? ;)</p>
      <p>If you somehow arrived here by accident, your account does not have permission to view this page.
      Click <a href="/">here</a> to return to the homepage, or click "Log out" and sign into the correct account.</p>
    </div>
  </div>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block title %}
  {% if post.published_date or perms.blog.manage_posts or user.id == post.author.id %}
    {{ post.title }}
  {% else %}
    George's Blog 404: Post not found
  {% endif %}
{% endblock %}


{% block content %}
</br>
<div class="content container">
  <div class="row">           
    <div class="col-md-8">  
  {% if post.published_date or perms.blog.manage_posts or user.id == post.author.id %}
    <div class="post">
      <h2>{{ post.title }}    
      {% if perms.blog.manage_posts or user.id == post.author.id %}
        <div class="btn-group" role="group" aria-label="post_actions_group">
        <a class="btn btn-secondary" href="{% url 'post_edit' pk=post.pk %}" id="post_edit"><i class="fas fa-edit"></i></a>
        {% if not post.published_date %}
          <a class="btn btn-secondary" href ="{% url 'post_publish' pk=post.pk %}" id="post_publish"><i class="fas fa-paper-plane"></i></a>
        {% endif %}
        <a class="btn btn-secondary" href="{% url 'post_remove' pk=post.pk %}" id="post_remove"><i class="fas fa-trash"></i></a>
      </div>
      {% endif %}</h2>
      
      {% if post.published_date %}
        <div class="date">
          <small><a href="{% url 'category' post.category|slugify %}">{{ post.category }}</a> | 
            {{ post.author.first_name }} {{ post.author.last_name}} | Published: {{ post.published_date }}</small>
        </div>
      {% endif %}
      <p>{{ post.text|safe }}</p>
    </div>
    <hr>
    <a class="btn btn-secondary" href="{% url 'add_comment_to_post' pk=post.pk %}" id="comment_add">Add comment</a>

    <hr>

    {% for comment in post.comments.all %}
      {% if perms.comment.manage_comments or comment.approved_comment %}      <!--maybe change later? or learn more about attributes-->
        <div class="comment">
          <div class="date">
            <small>
            {{ comment.created_date }}
          </small>
            {% if not comment.approved_comment %}
            <div class="btn-group" role="group">
              <a class="btn btn-secondary" href="{% url 'comment_remove' pk=comment.pk %}" id="comment_remove"><i class="fas fa-trash"></i></a>
              <a class="btn btn-secondary" href="{% url 'comment_approve' pk=comment.pk %}" id="comment_approve"><i class="fas fa-check"></i></a>
            </div>
            {% endif %}
          </div>
          <strong>{{ comment.author }}</strong>
          <p>{{ comment.text|linebreaksbr }}</p>
          <hr>
        </div>
      {% endif %}
    {% empty %}
      <p>No comments are here yet :(</p>
    {% endfor %}
  {% else %}
    <h2>404 :(</h2>
    <p>This post cannot be found.</p>
  {% endif %}
    </div>
  </div>
</div>
{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}

{% block title %}
  George's Blog - Draft posts list
{% endblock %}

{% block content %}
</br>
<div class="content container">
	<div class="row">           
		<div class="col-md-8">  
	{% for post in posts %}
		{% if post.author == user or perms.blog.manage_posts %}
    <div class="post">
			<h2><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a>
				<a class="btn btn-secondary btn-sm" href ="{% url 'post_publish' pk=post.pk %}" id="post_publish"><i class="fa fa-paper-plane"></i> Publish</a></a>
			</h2>
			<div class="date">
				<small><a href="{% url 'category' post.category|slugify %}">{{ post.category }}</a> | 
					{{ post.author.first_name }} {{ post.author.last_name }} | Published: {{ post.published_date }}</small>
			</div> 
				<p>{{ post.text|slice:":200"|safe }}...</p>
				<a href="{% url 'post_detail' pk=post.pk %}">Comments: {{ post.approved_comments.count }}
				<hr>
			</div>
	{% endif %}
	{% endfor %}
		</div>
	</div>
</div>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

{% block title %}
  George's Blog - Edit a new post
{% endblock %}

{% block content %}
</br>
<div class="content container">
  <div class="row">           
    <div class="col-md-8">
			<h2>New Post</h2>
			{{ form.media }}
			{% crispy form %}
		</div>
	</div>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}    <!-- this injects the html block into the content block in base.html. -->
</br>
<div class="content container">
  <div class="row">           
    <div class="col-md-8">       
  {% for post in posts %}
    <div class="post">
    <!-- pk means primary key, default auto generated and accessed by post.pk-->
    <!-- url 'post_detail' expects to match a url in urls.py-->
			<h2><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
			<div class="date">
				<small><a href="{% url 'category' post.category|slugify %}">{{ post.category }}</a> | 
					{{ post.author.first_name }} {{ post.author.last_name}} | Published: {{ post.published_date }}</small>
			</div> 
        <p>{{ post.text|slice:":200"|safe }}...</p>
        <a href="{% url 'post_detail' pk=post.pk %}">Comments: {{ post.approved_comments.count }}</a>
        <hr>
      </div>
    {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

blog/templates/blog/signup.html
{% extends 'blog/base.html' %}

{% block title %}
  George's Blog - Signup
{% endblock %}

{% block content %}
	<h2>Sign up</h2>
	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="btn btn-secondary" id="signup_submit">Sign up</button>
	</form>
{% endblock %}